# Generated by Django 3.2.20 on 2023-08-14 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pdfname_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTitle',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PdfName',
        ),
        migrations.AddField(
            model_name='mergedpdf',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app.PdfTitle'),
        ),
    ]
