# Generated by Django 3.2.20 on 2023-08-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230814_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mergedpdf',
            old_name='tag',
            new_name='pdf_name',
        ),
    ]
