# Generated by Django 3.2.20 on 2023-08-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_tag_mergedpdf_pdf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedpdf',
            name='pdf_name',
        ),
        migrations.RemoveField(
            model_name='mergedpdf',
            name='merged_name',
        ),
        migrations.AddField(
            model_name='mergedpdf',
            name='merged_name',
            field=models.ManyToManyField(blank=True, to='app.PdfTitle'),
        ),
    ]
