# Generated by Django 3.2.20 on 2023-08-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230814_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedpdf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='mergedpdf',
            name='merged_name',
        ),
        migrations.AddField(
            model_name='mergedpdf',
            name='merged_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PdfTitle',
        ),
    ]
